import { ago, el, formatTime, formatWhen, freshness, openLightbox, setStatus, slots } from "../util.js";

// Frames arrive every 5 min; the listing is scraped every ~10 min by Actions.
const OK_MIN = 30;
const WARN_MIN = 120;

// AI caption from scripts/caption_tankcam.py (every 2 h, 6 AM-6 PM Pacific).
function captionBlock(c, latest) {
  if (!c?.caption) return null;
  const frameAt = c.frame_captured_at ? new Date(c.frame_captured_at) : null;
  const older = c.frame_url !== latest.url;
  return el("div", { class: "caption" },
    el("div", { class: "caption-head" },
      el("span", { class: "badge", text: "AI caption" }),
      frameAt ? ` ${older ? "of the " : ""}${formatTime(frameAt)} frame` : ""),
    el("p", { text: c.caption }),
    c.oysters_visible || c.anomalies?.length
      ? el("div", { class: "caption-tags" },
        c.oysters_visible ? el("span", { class: "badge", text: `~${c.oyster_count} oysters visible` }) : null,
        (c.anomalies || []).map((a) => el("span", { class: "badge warn", text: `⚠ ${a}` })))
      : null,
    el("p", { class: "caption-foot", text: `Generated by ${c.model || "Claude"}; may be inaccurate.` }));
}

export function renderWebcam(data) {
  const { meta, body } = slots("webcam");
  const latest = data.latest;
  if (!latest) {
    body.replaceChildren(el("div", { class: "skeleton", text: "No Tankcam frame available." }));
    setStatus("webcam", "bad", data.error || "no frame");
    return;
  }

  const captured = latest.captured_at ? new Date(latest.captured_at) : null;
  const level = freshness(captured, OK_MIN, WARN_MIN);
  setStatus("webcam", level, captured ? `Latest frame ${ago(captured)}` : "capture time unknown");

  const stampText = captured ? `${formatWhen(captured)} · ${ago(captured)}` : latest.local_time;
  meta.replaceChildren(
    `Camera ${latest.camera ?? "?"} · frames every 5 min `,
    level !== "ok" ? el("span", { class: `badge ${level}`, text: level === "warn" ? "delayed" : "stale" }) : null,
  );

  const caption = `Live Tankcam, camera ${latest.camera ?? ""}, ${stampText}`;
  const hero = el("div", { class: "cam-hero" },
    el("img", {
      src: latest.url,
      alt: `Latest Tankcam frame from the tank room, ${stampText}`,
      onclick: () => openLightbox(latest.url, caption),
    }),
    el("span", { class: "stamp", text: stampText }));

  body.replaceChildren(
    hero,
    captionBlock(data.caption, latest),
    el("p", { class: "note" },
      "Images served from ",
      el("a", { href: data.source, text: "gannet" }),
      `. Checked ${formatTime(new Date(data.updated_at))}.`),
  );
}
